version: 2.1
jobs:
  compile:
   docker:
      - image: tyuzu/kernel:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh

workflows:
  version: 2.1
  build:
    jobs:
      - compile
